# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@dotbox/compiler-1.0.2" = {
      name = "_at_dotbox_slash_compiler";
      packageName = "@dotbox/compiler";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dotbox/compiler/-/compiler-1.0.2.tgz";
        sha512 = "GcYlK4wHrBwMVCAmNQSiCNofT94Pa4f3zH8JobgjtM6OcrhwPANndQEc+qu7VixT/B6//Jra7CbEZUkLTmHUVA==";
      };
    };
    "@dotbox/format-1.0.2" = {
      name = "_at_dotbox_slash_format";
      packageName = "@dotbox/format";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dotbox/format/-/format-1.0.2.tgz";
        sha512 = "l+Iyud6eTs9isrkDKtsG1WRprDIxqyzNBjS/RuBDP2wH0j21XHObFeFYI1ztzfN3pboW/74DxRNrAojBaEJBjQ==";
      };
    };
    "@littlethings/coder-1.1.4" = {
      name = "_at_littlethings_slash_coder";
      packageName = "@littlethings/coder";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@littlethings/coder/-/coder-1.1.4.tgz";
        sha512 = "0xJgWFfcpbzPfAkm+Ej1VrcLo6S8kE17uWgeotZ91REtaa60boo7CaiS6u6HqA/04vSKRaFBY6dx27nIFLlang==";
      };
    };
    "@littlethings/log-3.0.5" = {
      name = "_at_littlethings_slash_log";
      packageName = "@littlethings/log";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@littlethings/log/-/log-3.0.5.tgz";
        sha512 = "E/1wWHByV/3IeznXqM4EK7ZyNQGBwSggsSZ0bNZKCwV1gv3ySlLodWnNjzFsvyXslJypSdOr9K6c+9z7kF/T6Q==";
      };
    };
    "arg-5.0.2" = {
      name = "arg";
      packageName = "arg";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/arg/-/arg-5.0.2.tgz";
        sha512 = "PYjyFOLKQ9y57JvQ6QLo8dAgNqswh8M1RMJYdQduT6xbWSgK36P/Z/v+p888pM69jMMfS8Xd8F6I1kQ/I9HUGg==";
      };
    };
    "kleur-4.1.5" = {
      name = "kleur";
      packageName = "kleur";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz";
        sha512 = "o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==";
      };
    };
  };
in
{
  "@dotbox/cli" = nodeEnv.buildNodePackage {
    name = "_at_dotbox_slash_cli";
    packageName = "@dotbox/cli";
    version = "1.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@dotbox/cli/-/cli-1.0.2.tgz";
      sha512 = "qV9pm3vpyi6NhH4wGCrUNauKWtYHjFdCH/B6L/mN3CjUBdeW9rFSbubSd4U0BFLpjyBcJfFT9K6DVNZ5ewql5w==";
    };
    dependencies = [
      sources."@dotbox/compiler-1.0.2"
      sources."@dotbox/format-1.0.2"
      sources."@littlethings/coder-1.1.4"
      sources."@littlethings/log-3.0.5"
      sources."arg-5.0.2"
      sources."kleur-4.1.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A simple, easily readable configuration language.";
      homepage = "https://github.com/jakehamilton/dotbox";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@dotbox/format" = nodeEnv.buildNodePackage {
    name = "_at_dotbox_slash_format";
    packageName = "@dotbox/format";
    version = "1.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@dotbox/format/-/format-1.0.2.tgz";
      sha512 = "l+Iyud6eTs9isrkDKtsG1WRprDIxqyzNBjS/RuBDP2wH0j21XHObFeFYI1ztzfN3pboW/74DxRNrAojBaEJBjQ==";
    };
    dependencies = [
      sources."@dotbox/compiler-1.0.2"
      sources."@littlethings/coder-1.1.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A library for formatting DotBox files.";
      homepage = "https://github.com/jakehamilton/dotbox";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@dotbox/compiler" = nodeEnv.buildNodePackage {
    name = "_at_dotbox_slash_compiler";
    packageName = "@dotbox/compiler";
    version = "1.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@dotbox/compiler/-/compiler-1.0.2.tgz";
      sha512 = "GcYlK4wHrBwMVCAmNQSiCNofT94Pa4f3zH8JobgjtM6OcrhwPANndQEc+qu7VixT/B6//Jra7CbEZUkLTmHUVA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A library for compiling DotBox files.";
      homepage = "https://github.com/jakehamilton/dotbox";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
